name = "tinyaml_examples"
description = "Examples for TinyAML library"
version = "0.2.0"

authors = ["Jochen Lillich"]
maintainers = ["Jochen Lillich <hello@geewiz.dev>"]
maintainers-logins = ["geewiz"]

[[depends-on]]
tinyaml = "*"

[[pins]]
tinyaml = { path = ".." }
